const LOGIN_BEGIN="LOGIN_BEGIN";
const LOGIN_SUCCESS="LOGIN_SUCCESS";
const LOGIN_FAIL="LOGIN_FAIL";

const LOGOUT_BEGIN="LOGOUT_BEGIN";
const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
const LOGOUT_FAIL="LOGOUT_FAIL";

const REGISTER_BEGIN="REGISTER_BEGIN";
const REGISTER_SUCCESS="REGISTER_SUCCESS";
const REGISTER_FAIL="REGISTER_FAIL";

module.exports={
    LOGIN_BEGIN,LOGIN_SUCCESS, LOGIN_FAIL, 
    LOGOUT_BEGIN, LOGOUT_SUCCESS, LOGOUT_FAIL,
    REGISTER_BEGIN, REGISTER_SUCCESS, REGISTER_FAIL};